### ISSUE TITLE
Dimension mismatch problem

### ISSUE THREAD

**Issue by Rh-Dang** [yxKryptonite/OpenFMNav#5]
Traceback (most recent call last):
  File "/home/pai/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/pai/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/workspace/OpenFMNav/envs/habitat/utils/vector_env.py", line 202, in _worker_env
    observations = env.reset()
  File "/mnt/workspace/OpenFMNav/agents/sem_exp.py", line 113, in reset
    obs, info = super().reset()
  File "/mnt/workspace/OpenFMNav/envs/habitat/objectgoal_env21.py", line 154, in reset
    state = np.concatenate((rgb, depth, semantic), axis=2).transpose(2, 0, 1)
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 2 has 4 dimension(s)

The above is my error. this looks like the demension is mismatched. So I printed out their dimensions.

rgb shape: , (480, 640, 3)
depth shape: , (480, 640, 1)
semantic shape: , (480, 640, 1, 1)

It seems that the semantic tensor has one more dimension, so how do I solve this problem?

**Comment by yxKryptonite** [comment]
I didn't come across this issue in my environment. Maybe can you try to deduct one dimension by yourself and see how things go?

**Comment by yxKryptonite** [comment]
closed if no further questions

**Comment by yushanz** [comment]
@Rh-Dang Hi :) Have you solved this problem? I got the same issue and I am not sure how to solve it for now. Could you please share some insights?
